# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dražen Lazarević
email: drlatech@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer
  Mostly using Python programming language, that's why my design skills are on beginner level.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://drazenlazarevic.com" # the base hostname & protocol for your site
twitter_username: drlatech
github_username:  drlatech

# Build settings
markdown: kramdown
